nhnacademy-be7-2joping/2joping-book

- pom.xml
- src/main/java/com/nhnacademy/bookstore/bookset/book/entity/BookCategory.java
- src/main/java/com/nhnacademy/bookstore/bookset/book/entity/BookContributor.java
- src/main/java/com/nhnacademy/bookstore/bookset/category/controller/CategoryController.java
- src/main/java/com/nhnacademy/bookstore/bookset/category/dto/request/CategoryRequestDto.java
- src/main/java/com/nhnacademy/bookstore/bookset/category/dto/response/CategoryResponseDto.java
- src/main/java/com/nhnacademy/bookstore/bookset/category/repository/CategoryRepository.java
- src/main/java/com/nhnacademy/bookstore/bookset/category/service/CategoryService.java
- src/main/java/com/nhnacademy/bookstore/bookset/category/service/Impl/CategoryServiceImpl.java
feat: add bookcontributor entity & category setting
> feat: add bookcontributor entity & category setting

- pom.xml
- src/main/java/com/nhnacademy/bookstore/bookset/book/entity/Book.java
- src/main/java/com/nhnacademy/bookstore/bookset/publisher/controller/PublisherController.java
- src/main/java/com/nhnacademy/bookstore/bookset/publisher/dto/request/PublisherRequestDto.java
- src/main/java/com/nhnacademy/bookstore/bookset/publisher/dto/response/PublisherCreateResponseDto.java
- src/main/java/com/nhnacademy/bookstore/bookset/publisher/dto/response/PublisherResponseDto.java
- src/main/java/com/nhnacademy/bookstore/bookset/publisher/entity/Publisher.java
- src/main/java/com/nhnacademy/bookstore/bookset/publisher/exception/ExceptionAdvice.java
- src/main/java/com/nhnacademy/bookstore/bookset/publisher/exception/PublisherAlreadyExistException.java
- src/main/java/com/nhnacademy/bookstore/bookset/publisher/exception/PublisherNotFoundException.java
- src/main/java/com/nhnacademy/bookstore/bookset/publisher/repository/PublisherRepository.java
- src/main/java/com/nhnacademy/bookstore/bookset/publisher/service/PublisherService.java
- src/main/java/com/nhnacademy/bookstore/bookset/publisher/service/PublisherServiceImpl.java
출판사 CRUD 구현완료.
Swagger UI 테스트 완료.
> feat:publisher crud finish+swagger test finish

- src/main/java/com/nhnacademy/bookstore/user/member/controller/MemberAddressController.java
- src/main/java/com/nhnacademy/bookstore/user/member/service/impl/MemberAddressServiceImpl.java
- src/test/java/com/nhnacademy/bookstore/user/member/MemberAddressControllerTest.java
- src/test/java/com/nhnacademy/bookstore/user/member/MemberAddressServiceTest.java
> feat user-address-read

- src/main/java/com/nhnacademy/bookstore/bookset/publisher/dto/request/PublisherRequestDto.java
- src/main/java/com/nhnacademy/bookstore/bookset/publisher/repository/PublisherRepository.java
- src/main/java/com/nhnacademy/bookstore/bookset/publisher/service/PublisherService.java
- src/main/java/com/nhnacademy/bookstore/bookset/publisher/service/PublisherServiceImpl.java
- src/test/java/com/nhnacademy/bookstore/bookset/publisher/controller/PublisherControllerTest.java
- src/test/java/com/nhnacademy/bookstore/bookset/publisher/service/PublisherServiceImplTest.java
출판사 controller, ServiceImpl 테스트 코드 작성 완료.
> feat: publisher testcode finish

- src/main/java/com/nhnacademy/bookstore/shipment/mapper/CarrierMapper.java
- src/main/java/com/nhnacademy/bookstore/shipment/mapper/ShipmentPolicyMapper.java
> fix: mapper annotation 누락 수정

- src/main/java/com/nhnacademy/bookstore/bookset/contributor/controller/ContributorController.java
- src/main/java/com/nhnacademy/bookstore/bookset/contributor/controller/ContributorRoleController.java
- src/main/java/com/nhnacademy/bookstore/shipment/controller/CarrierController.java
- src/main/java/com/nhnacademy/bookstore/shipment/controller/ShipmentController.java
- src/main/java/com/nhnacademy/bookstore/shipment/controller/ShipmentPolicyController.java
front에서 해당 api를 가져오기 위해 매핑 path경로 수정
> fix: controller path /api/v1 추가

- src/test/java/com/nhnacademy/bookstore/bookset/contributor/controller/ContributorControllerTest.java
- src/test/java/com/nhnacademy/bookstore/bookset/contributor/controller/ContributorRoleControllerTest.java
- src/test/java/com/nhnacademy/bookstore/shipment/controller/CarrierControllerTest.java
- src/test/java/com/nhnacademy/bookstore/shipment/controller/ShipmentControllerTest.java
- src/test/java/com/nhnacademy/bookstore/shipment/controller/ShipmentPolicyControllerTest.java
test controller path 수정했습니다. 죄송합니다.
> fix: test controller path 수정

- src/main/java/com/nhnacademy/bookstore/common/error/dto/ErrorResponseDto.java
- src/main/java/com/nhnacademy/bookstore/common/error/enums/RedirectType.java
- src/main/java/com/nhnacademy/bookstore/common/error/exception/base/BadRequestException.java
- src/main/java/com/nhnacademy/bookstore/common/error/exception/base/ConflictException.java
- src/main/java/com/nhnacademy/bookstore/common/error/exception/base/ForbiddenException.java
- src/main/java/com/nhnacademy/bookstore/common/error/exception/base/NotFoundException.java
- src/main/java/com/nhnacademy/bookstore/common/error/exception/base/UnauthorizedException.java
- src/main/java/com/nhnacademy/bookstore/common/error/exception/user/address/AddressLimitToTenException.java
- src/main/java/com/nhnacademy/bookstore/common/error/exception/user/member/MemberDuplicateException.java
- src/main/java/com/nhnacademy/bookstore/common/error/exception/user/member/MemberNotFoundException.java
- src/main/java/com/nhnacademy/bookstore/common/error/exception/user/member/status/MemberStatusNotFoundException.java
- src/main/java/com/nhnacademy/bookstore/common/error/exception/user/member/tier/MemberTierNotFoundException.java
- src/main/java/com/nhnacademy/bookstore/common/error/handler/BaseExceptionHandler.java
- src/main/java/com/nhnacademy/bookstore/common/error/handler/GlobalExceptionHandler.java
- src/main/java/com/nhnacademy/bookstore/user/member/entity/Member.java
- src/main/java/com/nhnacademy/bookstore/user/member/entity/MemberAddress.java
- src/main/java/com/nhnacademy/bookstore/user/member/mapper/MemberAddressMapper.java
- src/main/java/com/nhnacademy/bookstore/user/member/service/MemberAddressService.java
- src/main/java/com/nhnacademy/bookstore/user/member/service/MemberService.java
- src/main/java/com/nhnacademy/bookstore/user/member/service/impl/MemberAddressServiceImpl.java
- src/main/java/com/nhnacademy/bookstore/user/member/service/impl/MemberServiceImpl.java
- src/main/java/com/nhnacademy/bookstore/user/memberStatus/entity/MemberStatus.java
- src/main/java/com/nhnacademy/bookstore/user/nonmember/entity/NonMember.java
- src/main/java/com/nhnacademy/bookstore/user/tier/entity/MemberTier.java
- src/test/java/com/nhnacademy/bookstore/user/member/MemberControllerTest.java
- src/test/java/com/nhnacademy/bookstore/user/member/address/MemberAddressControllerTest.java
GlobalException 
기존 상태코드, 상태, 메세지
-> redirect Type, Url, Data 추가 
및 member entity 등 클래스에 주석 추가
> feat GlobalException  fix, Member docs 추가

- src/main/java/com/nhnacademy/bookstore/shipment/repository/impl/ShipmentPolicyRepositoryImpl.java
배송정책 querydsl과 응답 dto 불일치 문제 수정
> fix: querydsl 순서 수정

- src/main/java/com/nhnacademy/bookstore/bookset/publisher/controller/PublisherController.java
- src/main/java/com/nhnacademy/bookstore/bookset/publisher/repository/PublisherRepository.java
- src/main/java/com/nhnacademy/bookstore/bookset/publisher/repository/PublisherRepositoryCustom.java
- src/main/java/com/nhnacademy/bookstore/bookset/publisher/repository/PublisherRepositoryImpl.java
- src/main/java/com/nhnacademy/bookstore/bookset/publisher/service/PublisherService.java
- src/main/java/com/nhnacademy/bookstore/bookset/publisher/service/PublisherServiceImpl.java
- src/test/java/com/nhnacademy/bookstore/bookset/publisher/controller/PublisherControllerTest.java
- src/test/java/com/nhnacademy/bookstore/bookset/publisher/service/PublisherServiceImplTest.java
기존에 작업했던 출판사를 수정했습니다.
출판사 전체 조회할 때 페이징 처리했습니다.
QueryDSL을 사용해서 dto로 변환하는 작업을 했습니다
> feat: paging publisher

- src/main/java/com/nhnacademy/bookstore/shipment/repository/impl/ShipmentPolicyRepositoryImpl.java
> fix: shipment-policy querydsl 순서수정

- src/main/java/com/nhnacademy/bookstore/admin/wrap/controller/WrapController.java
- src/main/java/com/nhnacademy/bookstore/admin/wrap/repository/WrapRepositoryCustom.java
- src/main/java/com/nhnacademy/bookstore/admin/wrap/repository/WrapRepositoryImpl.java
- src/main/java/com/nhnacademy/bookstore/admin/wrap/service/WrapService.java
- src/main/java/com/nhnacademy/bookstore/admin/wrap/service/WrapServiceImpl.java
- src/test/java/com/nhnacademy/bookstore/admin/wrap/controller/WrapControllerTest.java
- src/test/java/com/nhnacademy/bookstore/admin/wrap/service/WrapServiceTest.java
delete 기능 삭제하고 isActive로 수정했습니다. 
list 반환할 때 활성화 된 포장상품만 반환됩니다.
> fix: delete 기능 삭제 -> active

- src/main/java/com/nhnacademy/bookstore/common/config/AppConfig.java
- src/main/java/com/nhnacademy/bookstore/user/member/controller/MemberController.java
- src/main/java/com/nhnacademy/bookstore/user/member/dto/request/MemberCreateRequestDto.java
- src/main/java/com/nhnacademy/bookstore/user/member/entity/Member.java
- src/main/java/com/nhnacademy/bookstore/user/member/service/impl/MemberServiceImpl.java
> fix-user-signup-encodeByPasswordEncoder

- pom.xml
- src/main/java/com/nhnacademy/bookstore/user/member/controller/MemberAddressController.java
- src/main/java/com/nhnacademy/bookstore/user/member/dto/response/MemberAddressResponseDto.java
- src/main/java/com/nhnacademy/bookstore/user/member/entity/MemberAddress.java
- src/main/java/com/nhnacademy/bookstore/user/member/mapper/MemberAddressMapper.java
- src/main/java/com/nhnacademy/bookstore/user/member/repository/MemberAddressRepositroy.java
- src/main/java/com/nhnacademy/bookstore/user/member/service/impl/MemberAddressServiceImpl.java
- src/test/java/com/nhnacademy/bookstore/user/member/address/MemberAddressControllerTest.java
- src/test/java/com/nhnacademy/bookstore/user/member/address/MemberAddressServiceTest.java
> fix-address-header, mapper

- src/main/java/com/nhnacademy/bookstore/bookset/category/controller/CategoryController.java
> fix: category controller mapping url

- src/main/java/com/nhnacademy/bookstore/common/error/exception/user/member/MemberPasswordNotEqualException.java
- src/main/java/com/nhnacademy/bookstore/common/error/exception/user/member/status/MemberStatusNotFoundException.java
- src/main/java/com/nhnacademy/bookstore/user/member/controller/MemberAddressController.java
- src/main/java/com/nhnacademy/bookstore/user/member/controller/MemberController.java
- src/main/java/com/nhnacademy/bookstore/user/member/dto/request/MemberWithdrawRequesteDto.java
- src/main/java/com/nhnacademy/bookstore/user/member/dto/response/MemberWithdrawResponseDto.java
- src/main/java/com/nhnacademy/bookstore/user/member/entity/Member.java
- src/main/java/com/nhnacademy/bookstore/user/member/service/MemberService.java
- src/main/java/com/nhnacademy/bookstore/user/member/service/impl/MemberAddressServiceImpl.java
- src/main/java/com/nhnacademy/bookstore/user/member/service/impl/MemberServiceImpl.java
- src/test/java/com/nhnacademy/bookstore/user/member/MemberControllerTest.java
- src/test/java/com/nhnacademy/bookstore/user/member/MemberServiceImplTest.java
- src/test/java/com/nhnacademy/bookstore/user/member/address/MemberAddressControllerTest.java
회원 탈퇴 기능 추가입니다.
-Mapping
@PutMapping("/withdraw")
-Request 
public record MemberWithdrawRequesteDto(
String password
) {
}
-Response
public record MemberWithdrawResponseDto(
String name,
String message
) {
public MemberWithdrawResponseDto(String name) {
this(name, name + "님 탈퇴가 완료되었습니다."); // 고정된 메시지 설정
}
}
@PutMapping("/update")
Post -> PutMapping으로 수정했습니다.
> feat-user-withdraw

- src/main/java/com/nhnacademy/bookstore/cart/controller/CartController.java
- src/main/java/com/nhnacademy/bookstore/cart/dto/CartDeleteDto.java
- src/main/java/com/nhnacademy/bookstore/cart/dto/CartUpdateDto.java
- src/main/java/com/nhnacademy/bookstore/cart/mapper/CartMapper.java
- src/main/java/com/nhnacademy/bookstore/cart/repository/CartRepository.java
- src/main/java/com/nhnacademy/bookstore/cart/service/CartService.java
회원장바구니: DB를 통해 구현
비회원장바구니: redis를 통해 구현
회원: DB CRUD를 통해 구현 되었습니다. (SESSION 사용 X)
비회원: SESSION이 없는 상태에서 장바구니에 상품을 추가하면 SESSION이 쿠키에 저장되고 redis에 데이터가 추가되며 비회원 장바구니가 생성 됩니다.
-> cookie, session TTL을 따로 존재하지 않습니다. 상의 후, 설정하거나 임의 설정 필요
-> 상품 상세 페이지에 장바구니 추가를 위한 스크립트 추가하였습니다.
> feat: 회원, 비회원 모두 구현

- src/main/java/com/nhnacademy/bookstore/user/member/controller/MemberController.java
- src/main/java/com/nhnacademy/bookstore/user/member/dto/response/MemberPointResponse.java
- src/main/java/com/nhnacademy/bookstore/user/member/repository/MemberRepository.java
- src/main/java/com/nhnacademy/bookstore/user/member/service/MemberService.java
- src/main/java/com/nhnacademy/bookstore/user/member/service/impl/MemberServiceImpl.java
- src/test/java/com/nhnacademy/bookstore/user/member/MemberControllerTest.java
- src/test/java/com/nhnacademy/bookstore/user/member/MemberServiceImplTest.java
> feat: get point of member

- src/main/java/com/nhnacademy/bookstore/admin/wrap/repository/WrapManageRepository.java
- src/main/java/com/nhnacademy/bookstore/common/error/exception/bookset/book/BookNotFoundException.java
- src/main/java/com/nhnacademy/bookstore/orderset/order/service/OrderService.java
- 주문시 주문 도서에 포장 정보 테이블에 추가되도록 개선
> feat: Feature/order 도서 포장정보 테이블에 추가

- src/main/java/com/nhnacademy/bookstore/bookset/contributor/repository/ContributorRepository.java
기여자와 역할 가져오는 부분 이름순 정렬 추가했습니다.
> feat: add order by for find contributors with roles

- src/test/java/com/nhnacademy/bookstore/bookset/book/service/BookServiceImplTest.java
- src/test/java/com/nhnacademy/bookstore/bookset/tag/service/TagServiceTest.java
> feat: point-detail

- src/main/java/com/nhnacademy/bookstore/orderset/order/dto/request/OrderRequest.java
- src/main/java/com/nhnacademy/bookstore/orderset/order/entity/Order.java
- src/main/java/com/nhnacademy/bookstore/orderset/order/service/OrderService.java
- src/main/java/com/nhnacademy/bookstore/paymentset/payment_history/entity/PaymentHistory.java
- src/main/java/com/nhnacademy/bookstore/paymentset/payment_history/repository/PaymentHistoryRepository.java
- src/main/java/com/nhnacademy/bookstore/paymentset/payment_method/converter/PaymentMethodTypeConverter.java
- src/main/java/com/nhnacademy/bookstore/paymentset/payment_method/entity/PaymentMethod.java
- src/main/java/com/nhnacademy/bookstore/paymentset/payment_method/enums/PaymentMethodType.java
- src/main/java/com/nhnacademy/bookstore/paymentset/payment_method/exception/PaymentMethodNotFoundException.java
- src/main/java/com/nhnacademy/bookstore/paymentset/payment_method/repository/PaymentMethodRepository.java
- src/main/java/com/nhnacademy/bookstore/paymentset/status/entity/PaymentStatus.java
- src/main/java/com/nhnacademy/bookstore/paymentset/status/enums/PaymentStatusType.java
- src/main/java/com/nhnacademy/bookstore/paymentset/status/exception/PaymentStatusNotFoundException.java
- src/main/java/com/nhnacademy/bookstore/paymentset/status/repository/PaymentStatusRepository.java
- src/main/java/com/nhnacademy/bookstore/shipment/dto/request/ShipmentRequestDto.java
- 주문시 결제 정보와 배송 정보도 테이블에 저장하도록  적용
> feat: insert payment & shipment info when ordering

- src/main/java/com/nhnacademy/bookstore/review/service/ReviewServiceImpl.java
포인트적립을 리뷰에도 적용했습니다
하나의 주문상세에 중복 리뷰가 안되도록 예외처리를 했습니다
> feat: 리뷰달면 포인트적립, 중복 리뷰 안되게 예외처리

- src/main/java/com/nhnacademy/bookstore/review/repository/ReviewRepository.java
- src/main/java/com/nhnacademy/bookstore/review/service/ReviewServiceImpl.java
> fix: 리뷰 예외처리 관련 버그 픽스

- src/main/java/com/nhnacademy/bookstore/admin/wrap/controller/WrapController.java
- src/main/java/com/nhnacademy/bookstore/admin/wrap/service/WrapService.java
- src/main/java/com/nhnacademy/bookstore/admin/wrap/service/WrapServiceImpl.java
- src/main/java/com/nhnacademy/bookstore/imageset/repository/WrapImageRepository.java
> feat: add wrap image function 

- src/test/java/com/nhnacademy/bookstore/bookset/tag/service/TagServiceTest.java
> fix: tag service test 수정

- src/main/java/com/nhnacademy/bookstore/orderset/order/controller/OrderController.java
- src/main/java/com/nhnacademy/bookstore/user/member/entity/Member.java
임시로 member 월 byte 유형 int로 바꿈
이때 ddl-auto : validate 로 바꾸면 에러 남
> fix: temprally byte -> int

- src/main/java/com/nhnacademy/bookstore/bookset/book/repository/BookRepositoryCustom.java
- src/main/java/com/nhnacademy/bookstore/bookset/book/repository/BookRepositoryImpl.java
- src/main/java/com/nhnacademy/bookstore/common/error/exception/bookset/category/CategoryIdNullException.java
- src/test/java/com/nhnacademy/bookstore/bookset/book/repository/BookRepositoryImplTest.java
book repository 테스트 코드 작성 완료했습니다.
> test: add book repository test code

- src/test/java/com/nhnacademy/bookstore/point/controller/PointTypeControllerTest.java
- src/test/java/com/nhnacademy/bookstore/point/repository/PointTypeRepositoryTest.java
- src/test/java/com/nhnacademy/bookstore/point/service/PointTypeServiceTest.java
> feat: point type 테스트 코드 완료

- src/main/java/com/nhnacademy/bookstore/point/dto/response/GetDetailPointHistoriesResponse.java
- src/main/java/com/nhnacademy/bookstore/point/dto/response/GetPointHistoryResponse.java
- src/main/java/com/nhnacademy/bookstore/point/dto/response/GetSimplePointHistoriesResponse.java
포인트 사용 내역 point type id의 null 참조 문제로 인한 nullable 처리
> [Fix] point history fix

- src/main/java/com/nhnacademy/bookstore/common/error/exception/user/customer/CustomerNotFoundException.java
- src/main/java/com/nhnacademy/bookstore/orderset/order/service/OrderService.java
- src/main/java/com/nhnacademy/bookstore/user/customer/entity/Customer.java
- src/main/java/com/nhnacademy/bookstore/user/customer/service/CustomerService.java
- src/main/java/com/nhnacademy/bookstore/user/nonmember/entity/NonMember.java
- src/main/java/com/nhnacademy/bookstore/user/nonmember/service/NonMemberService.java
- src/main/resources/application-dev.properties
> fix: nonmember order register

- src/main/java/com/nhnacademy/bookstore/admin/wrap/controller/WrapController.java
- src/main/java/com/nhnacademy/bookstore/admin/wrap/repository/WrapRepository.java
- src/main/java/com/nhnacademy/bookstore/admin/wrap/service/WrapService.java
- src/main/java/com/nhnacademy/bookstore/admin/wrap/service/WrapServiceImpl.java
- src/main/java/com/nhnacademy/bookstore/bookset/book/controller/BookController.java
- src/main/java/com/nhnacademy/bookstore/bookset/book/dto/request/BookCreateHtmlRequestDto.java
- src/main/java/com/nhnacademy/bookstore/bookset/book/dto/response/BookContributorResponseDto.java
- src/main/java/com/nhnacademy/bookstore/bookset/book/dto/response/BookResponseDto.java
- src/main/java/com/nhnacademy/bookstore/bookset/book/entity/BookContributor.java
- src/main/java/com/nhnacademy/bookstore/bookset/book/repository/BookContributorRepository.java
- src/main/java/com/nhnacademy/bookstore/bookset/book/repository/BookRepositoryCustom.java
- src/main/java/com/nhnacademy/bookstore/bookset/book/repository/BookRepositoryImpl.java
- src/main/java/com/nhnacademy/bookstore/bookset/book/service/BookService.java
- src/main/java/com/nhnacademy/bookstore/bookset/book/service/impl/BookServiceImpl.java
- src/main/java/com/nhnacademy/bookstore/bookset/category/controller/CategoryController.java
- src/main/java/com/nhnacademy/bookstore/bookset/category/repository/CategoryRepository.java
- src/main/java/com/nhnacademy/bookstore/bookset/publisher/repository/PublisherRepositoryImpl.java
- src/main/java/com/nhnacademy/bookstore/bookset/tag/dto/TagResponseDto.java
- src/main/java/com/nhnacademy/bookstore/bookset/tag/entity/BookTag.java
- src/main/java/com/nhnacademy/bookstore/bookset/tag/repository/BookTagRepository.java
- src/main/java/com/nhnacademy/bookstore/bookset/tag/service/TagService.java
- src/main/java/com/nhnacademy/bookstore/bookset/tag/service/TagServiceImpl.java
- src/main/resources/logback.xml
- src/test/java/com/nhnacademy/bookstore/admin/wrap/service/WrapServiceTest.java
> feature : logback

- logs/rolling-app.log
- src/main/java/com/nhnacademy/bookstore/orderset/order/service/OrderService.java
- 쿠폰이 아예 없는 회원이 결제 시도하는 경우에도 예외가 발생하는 문제 해결
> fix: payment issue for members without coupons
